// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1POWVS8XtA-bGW9rCLE2i-YuH4sVyNOs',
    appId: '1:1025977464909:web:97f50c84051dc9f8240404',
    messagingSenderId: '1025977464909',
    projectId: 'packageguard-d517e',
    authDomain: 'packageguard-d517e.firebaseapp.com',
    storageBucket: 'packageguard-d517e.appspot.com',
    measurementId: 'G-LG4QKQVM16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTAM0nUnbpCjQ5opm63QFCu2xermvfFxI',
    appId: '1:1025977464909:android:f12401f597a37f16240404',
    messagingSenderId: '1025977464909',
    projectId: 'packageguard-d517e',
    storageBucket: 'packageguard-d517e.appspot.com',
    databaseURL:
        'https://packageguard-d517e-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSdm1Hlof2xvtWfn8pZLTidkrfZJ2-Sig',
    appId: '1:1025977464909:ios:728240b9b4c7d84f240404',
    messagingSenderId: '1025977464909',
    projectId: 'packageguard-d517e',
    storageBucket: 'packageguard-d517e.appspot.com',
    iosBundleId: 'com.example.packageguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSdm1Hlof2xvtWfn8pZLTidkrfZJ2-Sig',
    appId: '1:1025977464909:ios:00ca8697c34ec6b0240404',
    messagingSenderId: '1025977464909',
    projectId: 'packageguard-d517e',
    storageBucket: 'packageguard-d517e.appspot.com',
    iosBundleId: 'com.example.packageguard.RunnerTests',
  );
}
